dist: trusty
language: node_js
node_js:
  - '12'
env:
  global:
    - HUGO_VERSION=0.58.2
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
install:
  - yarn install
script:
  - yarn build

