[context.production.environment]
HUGO_VERSION = "0.55"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[build.environment]
  YARN_VERSION = "1.16.0"
  NPM_VERSION = "6.9.0"
  HUGO_VERSION = "0.55"

[build]
  command = "yarn build"
  publish = "dist"
